### PR TITLE
Image Upload

### PR DESCRIPTION
**Pull request by raveen-singh**
This PR adds the ability to upload images from the create unit modal.

**Acceptance Criteria**
- [ ] Refresh python modules by running `pip3 install -r requirements.txt`
- [ ] Run the SQL scripts (cleanup, create, populate)
- [ ] Navigate to the frontend and add an image to upload
- [ ] Check to make sure the image appears in the images folder, prefixed with a UUID.
- [ ] Query the DB to ensure that the filename is saved correctly.

### CODE REVIEW

**Review by ragizaki — CHANGES_REQUESTED** [review]
When I create a unit and click submit, the image is being added to the images folder, but flask is returning an error and the rest of the onSubmit function in the UnitForm is not being run (i.e. everything after the line `const res = await axios.post('/api/unit/create')`. The `console.log(res)` and `handleClose()` lines are not being run. The flask error is really long, but a snippet is 

`Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "C:\Users\zakim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)`

**Comment by raveen-singh** [comment]
> 

looking into this

**Comment by raveen-singh** [comment]
> When I create a unit and click submit, the image is being added to the images folder, but flask is returning an error and the rest of the onSubmit function in the UnitForm is not being run (i.e. everything after the line `const res = await axios.post('/api/unit/create')`. The `console.log(res)` and `handleClose()` lines are not being run. The flask error is really long, but a snippet is
> 
> `Debugging middleware caught exception in streamed response at a point where response headers were already sent. Traceback (most recent call last): File "C:\Users\zakim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 2548, in __call__ return self.wsgi_app(environ, start_response)`

looking into this

**Review by ragizaki — APPROVED** [review]
nice

**Review by jennybai01 — CHANGES_REQUESTED** [review]
works as desired. however, dont use absolute path to store image bc its not compatible across devices if we're pushing images to the repo (which we have to for our milestone 2 production data). if anything, in the backend get image endpoint, we can use a python system function to retrieve the current absolute directory path and combine with the image relative path if we have to.

**Comment by raveen-singh** [comment]
> works as desired. however, dont use absolute path to store image bc its not compatible across devices if we're pushing images to the repo (which we have to for our milestone 2 production data). if anything, in the backend get image endpoint, we can use a python system function to retrieve the current absolute directory path and combine with the image relative path if we have to.

good catch, I can look into storing the relative path.

**Comment by raveen-singh** [comment]
> > works as desired. however, dont use absolute path to store image bc its not compatible across devices if we're pushing images to the repo (which we have to for our milestone 2 production data). if anything, in the backend get image endpoint, we can use a python system function to retrieve the current absolute directory path and combine with the image relative path if we have to.
> 
> good catch, I can look into storing the relative path.

Image paths stored in the db are now relative. They look like this `/images/9acbfa9dtest.jpg`. The write currently points to the file path of the os (we can change that if we need to put this into a prod env).

**Review by jennybai01 — APPROVED** [review]

**Pull request merged**
